version: "3"
services:

  dgraph:
    image: dgraph/dgraph:latest

  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "none"
    ports:
      - "$neo4j_http:7474"
      - "$neo4j_bolt:7687"

  # your go development workspace
  dev:
    # docker exec -t -i workspace /bin/bash
    # or docker-compose run dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # these 2 have to be args instead of normal env vars
        # or won't work during build
        DEV_EXPOSE_PORT: $DEV_EXPOSE_PORT
        DEV_EXPOSE_PORT_FE: $DEV_EXPOSE_PORT_FE
        DEV_WORKSPACE: $DEV_WORKSPACE
    volumes:
      # map ./ in your host to /go/src/ in the container
      - ".:/go/src/$DEV_WORKSPACE"
    ports:
      - $DEV_HOST_PORT:$DEV_EXPOSE_PORT
      - $DEV_HOST_PORT_FE:$DEV_EXPOSE_PORT_FE
